model:
  model_id: "../models/openai/whisper-large-v3-turbo" # relative path from repo root path
  torch_dtype: "auto"    # Options: "auto", "float16", "float32"
  device_map: "auto"     # Options: "auto", "cpu", "cuda"
  use_safetensors: true  # Use safetensors for secure loading

pipeline:
  source_language: "english"

main:
  audio_file: "audios/k2sbKTEhVe4.mp3"
  output_srt: "output/k2sbKTEhVe4.srt"
  output_txt: "output/k2sbKTEhVe4.txt"
  translated_srt: "output/k2sbKTEhVe4_translated.srt"

translation_model:
  model_id: "../models/Qwen/Qwen2.5-7B-Instruct"  
  torch_dtype: "auto"    # Options: "auto", "float16", "float32"
  device_map: "cuda"     # Options: "auto", "cpu", "cuda"
  batch_size: 20
  # max_length: 512  # Maximum length for the translated text